### ISSUE TITLE
Hook up HomeScreen to Activity Selection Screens

### ISSUE THREAD

**Issue by LuzCappuccino** [FBU2018-L3/1-Up#14]
Need to simply pass through a string that tells up which category we want to view on activity selection. Lucie and I will work together to wire these things together.

**Comment by LuzCappuccino** [comment]
Connection was a success! Now we have a flow from login, to activity buttons, to activity selection.

**Comment by lucieleblanc** [comment]
[connect home to activity selection](https://github.com/FBU2018-L3/1-Up/commit/91a667146286bf218b10949e48992b32ed1cd1b2)
