### ISSUE TITLE
Event Class Creation and Implementation 

### ISSUE THREAD

**Issue by LuzCappuccino** [FBU2018-L3/1-Up#2]
Work on creating and implementing an "event" class that will tie together users with their respective completed activities. Test proper event creation by seeing if the user can fetch all of their "events".

**Comment by lucieleblanc** [comment]
see commits [create and register Event model](https://github.com/FBU2018-L3/1-Up/commit/ac4bff82fdbc95b9ebc4c7361c1a0e0027341c84) and [create Event.Query](https://github.com/FBU2018-L3/1-Up/commit/431222698285caf643a19ec3d884c82221c64907), along with [add Parse annotation, activity for testing](https://github.com/FBU2018-L3/1-Up/commit/b493c96ce49cb502981c51a675729101c3fccd9c)

**Comment by lucieleblanc** [comment]
and one more [modify Event.Query](https://github.com/FBU2018-L3/1-Up/commit/fae8b2aa34396883b14f523433c18978f980d9da)
