### ISSUE TITLE
Create feed and display recent Events

### ISSUE THREAD

**Issue by lucieleblanc** [FBU2018-L3/1-Up#26]

**Comment by LuzCappuccino** [comment]
Reminder to self: Bring over the parse relative data model!

**Comment by LuzCappuccino** [comment]
Signing  off for today. What went down: 
1. Item views for individual events got set up!
2. Adapter for events was written was is ready to be reused for  timeline fragment. 
3. User feed on the profile screen can see a populated feed filled with events from the past week. (need more test data to make sure though!)

Latest commit: [Timeline displays events associated with User](https://github.com/FBU2018-L3/1-Up/commit/8a725c55d2a04daa1ff7d4cc9c41a0c47944515a)

**Comment by LuzCappuccino** [comment]
Merge commit is [here](https://github.com/FBU2018-L3/1-Up/commit/7264aca0f18befa22735517f35d4b0581b33dcde)
